### ISSUE TITLE
Add header only one time

### ISSUE THREAD

**Issue by jodjo86** [angelovangel/fastq-stats#5]
Hi,

Do you think it is possible to add the header only once. The ```-s``` argument controls whether to have no header or one header per fastq file.

example command I am using:
```parallel faster -ts ::: /path/to/fastq/*.fastq.gz > out.tsv```

thank you

**Comment by angelovangel** [comment]
Hi,
it is not possible directly. One solution would be to run `faster -t example.fastq.gz > out.tsv` once to get the header and then in subsequent runs with `parallel` append to the previous output:
`parallel faster -ts ::: /path/to/fastq/*.fastq.gz >> out.tsv`

**Comment by jodjo86** [comment]
Good idea. Thank you
