### ISSUE TITLE
Expected @ at record start.

### ISSUE THREAD

**Issue by AlcaArctica** [angelovangel/fastq-stats#6]
I am getting the following error:

```
faster -t 20240327-54345-2B1-LAB5262-L144596.bam_dcc.fastq.gz > faster_results.tsv 
thread 'main' panicked at src/main.rs:404:14:
Failed to parse fastq record!: Custom { kind: Other, error: "Expected @ at record start." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So it seems as if the fastq file is corrupt? However, other programs had no problem with this file (e.g. assembled with hifiasm without hitch). Any ideas?

Thank you

**Comment by AlcaArctica** [comment]
Okay I just checked, and the fastq file does start with @:

```
gunzip -c 20240327-54345-2B1-LAB5262-L144596.bam_dcc.fastq.gz > uncompressed.fastq
head uncompressed.fastq 
@m54345U_240329_012903/73926044/ccs
TACAAACATGACAAGGGGAAGGAAAAGCCTTTCAATAGAACCTGA
```
It looks like this:
<img width="486" alt="image" src="https://github.com/angelovangel/faster/assets/38464874/dd9089ea-71f1-4a1f-9a33-f87165e6ab06">

So why this error?

**Comment by angelovangel** [comment]
Hi,
can you try faster2 (it's faster and I maintain it more now)?
https://github.com/angelovangel/faster2
It takes similar parameters like faster.
If this doesn't work may be try [seqkit stats](https://bioinf.shenwei.me/seqkit/usage/) to get similar metrics...

**Comment by AlcaArctica** [comment]
Oh great, I hadn't realised that there is a new version! Faster2 works without problem on my file (and probably faster). Thank you so much for this amazing tool!
